ignore_patterns:
- devel
sources:
  asyncapi-website:
    url: https://github.com/asyncapi/website
    docs_path: markdown/docs
    manual: true
    docs_url: https://www.asyncapi.com/docs
  asyncapi-json-schema:
    manual: true
    docs_url: https://github.com/asyncapi/website/blob/master/config
  asyncapi-usecases:
    manual: true
    docs_url: https://www.asyncapi.com/casestudies
